  # Install dependencies and build your application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

 

  # Deploy to App Engine
  - name: 'gcr.io/google-appengine/app-engine-python'
    args: ['gcloud', 'app', 'deploy', '--version', '1.0.0', '--project', 'reacthomeloan']

 

# Specify substitutions for dynamic values
# substitutions:
#   _PROJECT_ID: YOUR_PROJECT_ID
#   _VERSION: 1.0.0

 

# Optionally, you can specify the build timeout and other settings.
# timeout: 1200s
# queueTtl: 3600s
# options:
#   substitutionOption: ALLOW_LOOSE
#   logging: LEGACY